

name: Publish Python package

on:
  push:
    tags:
      - "*"   # Only run when you push a version tag, e.g. v0.1.0

# install poetry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        run:
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Assign version
        run: |
          export revision=$(git describe --tag | grep -E "^[0-9]+\.[0-9]+\.[0-9A-Za-z]+" -o)
          echo "VERSION=$revision" >> $GITHUB_ENV

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build package
        run: |
          poetry version $revision
          poetry build